### ISSUE TITLE
Implements thumbnails generation for Esri REST services

### ISSUE THREAD

**Issue by capooti** [cga-harvard/hypermap#1]
@jmwenda can you help with me with this?
Basically you should test what can be done with the arcrest library, and figure out a way to get a thumbnail for a layer.
After figuring it out, we can discuss how to integrate your work in code base.

**Comment by jmwenda** [comment]
Sample image servers to test with.

http://services.kgs.ku.edu/arcgis/rest/services/IMAGERY_LOCAL/Atchison_County_2012/ImageServer
http://sampleserver6.arcgisonline.com/arcgis/rest/services/Toronto/ImageServer
http://services.kgs.ku.edu/arcgis/rest/services/ - has a wealth of imageservers
